### PR TITLE
Implemented responsive clone of The Next Web landing page.

### PR DESCRIPTION
**Pull request by pointerish**
We have implemented a responsive clone of The Next Web landing page. 

- Navbar
- Articles
- Footer

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required

### Hello team,

**Great job on your project.**

**There are, however, a few changes needed before the project can be approved.**

1). **For the desktop screen and medium screens, there should be a search icon at the rightmost side of the sub-navigation row.**

original | clone
---------| -------
subnav_original | subnav_clone

2). **For desktop screen size, increase the text font size for the top navigation row. Also, the titles are not displaying properly. They appear to be cut off at the top. Please fix that.**

original | clone
---------| -------
mainnav_original  | mainnav_clone

3). **Navigation bar for the small screen, the icons should each have a left border. Also, reduce the spacing between them.**

original | clone
---------| -------
hamburger_original | hamburger_clone

4). **Add the clock and share icons at the bottom of the sections with the background image, as it is in the original. For the large background image, add the date at the rightmost side as it is in the original.**

original | clone
---------| -------
bigimage_original  | bgimage_clone

5). **TNW logo is not displaying properly at 1024px width**

tnw_clone

6). **Latest funding section**

-  **At 1024px**

1.  **The subtitles should display below the large title.**

2.   **There should be three cards displaying and not four. The column for the fourth card is empty.** 

original | clone
---------| -------
latestfunding_original  | latestfunding_clone

-  **At (>769px), the subtitles should display on a single line and not multiple lines.**

7). **Categories (Apps, Gear, Tech, etc) section**

- **Some content, on the leftmost section, is cut off at 1024px.**

hardfork_clone

- **Each section should take the full width of the page for small screen sizes(<767px).**

original | clone
---------| -------
fork_original  | fork_clone

8). **Latest deals section**

- **The captions below the image title should be price figures and not text.**

- **Add the subtitle, see all deals, at the rightmost part of the section as it is in the original.**

original | clone
---------| -------
latestdeals_original | latestdeals_clone

9). **You have a file titled ' on your git repo, please remove it. It has the same content as the .gitignore file.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**
- [ ] On scrolling the TNW logo is missing. 

**Original**

chrome-capture (21)

**Clone**

chrome-capture (22)

- [x] Your webpage has unnecessary padding. Please resolve this issue and increase the size of each item as present on the original page. 

**Clone**

chrome-capture (23)

**Original**

chrome-capture (24)

- [x] Please remove extra space.

**Clone**

chrome-capture (25)

**original**

chrome-capture (26)

- [ ] Please remove unnecessary space. 

**Clone**

chrome-capture (27)

**Original**

chrome-capture (28)

- [x] You need to work on your footer. Items are not aligned correctly. Please have a look. 

**Original**

chrome-capture (29)

**Clone**

chrome-capture (30)

- [ ] Before submitting the next re-review please be sure that your project looks exactly the clone of https://thenextweb.com/ on all modes(Tablet, small and large screens). 


-[ ] **Latest deals section**

- The captions below the image title should be price figures and not text.

- Add the subtitle, see all deals, at the rightmost part of the section as it is in the original.

**Original**

95794666-1857f000-0cf1-11eb-99ac-eb220046bf71

**Clone**

95794676-21e15800-0cf1-11eb-94a2-f78a7ec71b8b


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required

### Hello team,

**Great job implementing the changes. However, there are some more fixes needed.**

1). **There are two requests by the previous tse that haven't yet been implemented.**

- 
tnw_clone

- **Add the subtitle, see all deals, at the rightmost part of the section as it is in the original. See the circled area in the screenshot below.**

latest_original

2). **Your latest funding section does not display the subtitles on 1024px width. See the circled area on the screenshot below.**

original | clone
---------| -------
funding_original | latest_clone

3). **Align the columns properly in each row for categories (Apps, Gear, Tech, etc) section, on 1024px width. Example, you notice on the screenshot below, Hardfork is not on the same line as Apps and Gear. Check the other rows too.**

fork_clone

4). **The navbar should have a sticky position on small screen sizes as well. (<768px).**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

**Comment by pointerish** [comment]
Hi TSEs,

We have fixed/added all the required changes/additions except for the scrolling navbar logo effect. This uses JavaScript and we are not using JavaScript just yet but HTML & CSS only.

If this is possible by just using CSS we would appreciate some guidance since all of our Google searches threw no results for a CSS only scrolling effect like that on the navbar. All the solutions use JavaScript.

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @imran5644 and @pointerish  . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] Desktop the main 3 images section is not correctly aligned
image

- [x] In tablet mode the elements are overlaping
image

- [x] in tablet footer doesn't look as original
image

- [ ] website goes outside the boundaries of the screen-size
image

- [x] The navbar seem to have a height that uses ```vh````, this makes the navbar to distort when there are taller screen sizes.
image
image

- [x] in mobile Other sections Elements doesn't look as expected
image

- [x] In mobile footer doesn't look as expected
image


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by pointerish** [comment]
Hi all,

Thank you for all the feedback provided here. We have fixed all the errors except for "website goes outside the boundaries of the screen-size". We were not able to replicate this error for small resolutions. See the following: https://ibb.co/r0W2FNB 

Appreciate all the help!

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] The lates deals doesn't look as the original
image

- [ ] The website goes outside the boundaries at 320px the smallest mobile screen in a smartphone.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by pointerish** [comment]
Hi @jubaan,

Thank you for all the feedback provided here. We have fixed all the errors except for "website goes outside the boundaries of the screen-size". We were not able to replicate this error for small resolutions. See the following: https://ibb.co/r0W2FNB

Appreciate all the help!

**Comment by jubaan** [comment]
> Hi @jubaan,
> 
> Thank you for all the feedback provided here. We have fixed all the errors except for "website goes outside the boundaries of the screen-size". We were not able to replicate this error for small resolutions. See the following: https://ibb.co/r0W2FNB
> 
> Appreciate all the help!

Thanks for the message @pointerish, The website is breaking in Chrome and Opera Browsers. Not in Firefox. I'm guessing you are using the last one. I'm going to approve it but please check the project in other browsers and try to replicate, it the issue still persists try to fix it before merging to master.

**Review by jubaan — APPROVED** [review]
# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

#### :clap: :clap: Great job :hammer_and_pick:!! There are no more issues left to be addressed. 

## You may now merge to master! :+1: :100:

## See you at the top :rocket:!

# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

**Comment by pointerish** [comment]
Hi @jubaan, I am actually using Chrome not Firefox. I will surely investigate it to make sure I understand why it's not working for you. Because of learning purposes. Thank you for the help and for all the feedback provided. Have a nice day!

**Pull request merged**
